name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Installer les dépendances
        run: npm install --legacy-peer-deps

      - name: Donner des permissions d'exécution à Jest
        run: chmod +x ./node_modules/.bin/jest
        
      - name: Installer Jest
        run: npm install -g jest
        
      - name: Lancer les tests
        run: npm test
